[package]
name = "manager_lib_tester"
version = "0.1.0"
authors = ["kumarmo2 <mohitkumar1015795@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manager = { path = "../manager" }
serde = "1.0.106"
